version: "2"
networks:
  mynet:
    driver: overlay
services:
  db:
    container_name: "db"
    image: postgres
    networks:
      - mynet
    ports:
       - "5432:5432"
    environment:
      - POSTGRES_USER=ticketmonster
      - POSTGRES_PASSWORD=ticketmonster-docker
  modcluster:
    container_name: "modcluster"
    networks:
      - mynet
    image: karm/mod_cluster-master-dockerhub
    environment:
      - MODCLUSTER_NET=192. 172. 10. 179. 213.
      - MODCLUSTER_PORT=80
    ports:
       - "80:80"
  wildfly:
    image: rafabene/wildfly-ticketmonster-ha
    #build: ../Dockerfiles/ticketmonster-ha/
    networks:
      - mynet
